export const IndexingAuditContent = {
  title: "Indexing",
  description:
    "Checks what search actually knows about this site: which lists are excluded from the index, how much of each list is indexed, whether sampled items are findable and up to date, and which managed properties come back.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  moduleVersion: "Module",
  backToRuns: "All runs",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  review: "Review",
  tabs: {
    overview: "Overview",
    lists: "Lists",
    items: "Item checks",
    properties: "Managed properties",
  },
  stats: {
    lists: "Lists checked",
    excluded: "Excluded from search",
    coverage: "Index coverage",
    indexed: "Indexed items",
    expected: "Items in lists",
    below: "Lists below target",
    missing: "Sampled items missing",
    stale: "Sampled items stale",
    properties: "Managed properties",
  },
  tileInfo: {
    lists: "Lists and libraries included in this run.",
    excluded: "Lists with search indexing turned off in list settings, so their items never appear in results.",
    coverage: "Indexed items as a share of the items reported by the lists.",
    indexed: "Items search reports under each list path.",
    expected: "Item counts reported by SharePoint for the same lists.",
    below: "Lists whose coverage is under the target set for this run.",
    missing: "Sampled items that returned nothing for a Path query.",
    stale: "Sampled items whose indexed copy is older than the item itself, so a crawl is pending.",
    properties: "Managed properties returned on a sample result, a quick view of what is retrievable.",
  },
  charts: {
    coverage: "Coverage by list",
    indexed: "Indexed items by list",
    crawl: "Lists by crawl setting",
    items: "Sampled items by index state",
  },
  cardInfo: {
    coverage: "Percentage of each list that search can see. Anything well under 100% needs a look.",
    indexed: "Indexed item counts per list, so you can see where the bulk of the index sits.",
    crawl: "Lists allowed in search against lists excluded in list settings.",
    items: "Result of the per item spot check: found, missing, or found but out of date.",
  },
  columns: {
    title: "List",
    template: "Template",
    crawl: "Search",
    permissions: "Permissions",
    items: "Items",
    indexed: "Indexed",
    coverage: "Coverage",
    modified: "Last item modified",
    item: "Item",
    list: "List",
    state: "State",
    itemModified: "Item modified",
    indexedModified: "Indexed copy",
    property: "Managed property",
    actions: "Actions",
  },
  crawl: { on: "Indexed", off: "Excluded" },
  actions: {
    searchSettings: "Search settings (advanced settings)",
    permissions: "List permissions",
    settings: "List settings",
  },
  state: { indexed: "Indexed", missing: "Missing", stale: "Stale" },
  unique: "Unique",
  inherited: "Inherited",
  siteExcluded:
    "This site is set not to appear in search results, so nothing under it will be indexed until that is turned back on.",
  coverageHint:
    "Coverage compares the item count SharePoint reports with the number of items search returns for the list path. Folders, versions and security trimming can make the two differ slightly.",
  empty: {
    title: "No audit yet",
    description: "Run the audit to check crawl settings, index coverage and sampled items.",
  },
  itemsOff: "Item checks were off for this run.",
  coverageOff: "Coverage checks were off for this run.",
  search: "Search lists",
  searchItems: "Search items",
  searchProperties: "Search properties",
} as const;
