export const AnalyticsAuditContent = {
    title: "Analytics audit",
    description: "Views, viewers and time spent for every page and file, read from the same site endpoints the SharePoint usage panel uses rather than from search.",
    moduleVersion: "Version",
    historyTitle: "Previous analytics runs",
    configTitle: "Analytics settings",
    run: "Run analytics audit",
    rerun: "Run again",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    backToRuns: "Back to runs",
    exportCsv: "Export analytics",
    tabs: {
        overview: "Overview",
        pages: "Pages",
        files: "Files",
        days: "By day",
        unviewed: "Never viewed",
    },
    windows: {
        today: "Today",
        last7: "7 days",
        last30: "30 days",
        last90: "90 days",
        allTime: "All time",
        label: "Window",
    },
    sections: {
        traffic: "Traffic",
        audience: "Audience",
        content: "Content",
    },
    stats: {
        views: "Views",
        unique: "Unique viewers",
        visits: "Site visits",
        timePerView: "Average time per view",
        timePerViewer: "Average time per viewer",
        pages: "Pages",
        files: "Files",
        viewed: "Pages viewed",
        unviewed: "Pages never viewed",
        busiestDay: "Busiest day",
        busiestHour: "Busiest hour",
        days: "Days measured",
        change: "Change",
    },
    tileInfo: {
        views: "Every view recorded in the window. SharePoint counts a view per item, so one person reading three pages counts three times.",
        unique: "Distinct viewers, counted per item and summed, so the same person on two pages counts twice.",
        visits: "Days with at least one recorded view, summed across the window: the closest this data gets to a session count.",
        timePerView: "Time spent divided by views.",
        timePerViewer: "Time spent divided by unique viewers.",
        pages: "Pages read from the Site Pages library.",
        files: "Files read from document libraries, when file analytics were included.",
        viewed: "Pages with at least one view in the window.",
        unviewed: "Pages nobody has opened in the window. The place to start when trimming a site.",
        busiestDay: "The single day with the most views in the measured period.",
        busiestHour: "The hour of the day with the most views, where the tenant reports hourly data.",
        days: "Days of history the run asked for.",
        change: "Movement against the window immediately before this one.",
    },
    charts: {
        viewsByDay: "Views by day",
        viewersByDay: "Viewers by day",
        viewsByHour: "Views by hour of day",
        viewsByWeekday: "Views by day of week",
        viewsByFolder: "Views by folder",
        viewsByOrgUnit: "Views by organisational unit",
        viewsByFileType: "Views by file type",
        topPages: "Most viewed pages",
        topFiles: "Most viewed files",
        timeByFolder: "Time spent by folder",
    },
    cardInfo: {
        viewsByDay: "Daily totals for the site over the measured period.",
        viewersByDay: "Distinct viewers per day.",
        viewsByHour: "When people read, in the browser's timezone. Empty where the tenant does not report hourly data.",
        viewsByWeekday: "Which days of the week carry the traffic.",
        viewsByFolder: "Views grouped by the folder each page sits in.",
        viewsByOrgUnit: "Views grouped by the owning area, using the column named in settings.",
        viewsByFileType: "Views grouped by file extension.",
        topPages: "The pages carrying the traffic.",
        topFiles: "The files people actually open.",
        timeByFolder: "Where reading time goes, rather than where clicks go.",
    },
    columns: {
        title: "Title",
        list: "List",
        folder: "Folder",
        orgUnit: "Area",
        type: "Type",
        views: "Views",
        unique: "Viewers",
        time: "Time spent",
        perView: "Per view",
        modified: "Modified",
        open: "Open",
    },
    notes: {
        sampled: "This tenant does not answer the site wide activity endpoints, so the daily charts are summed from the pages that were read.",
        perItem: "SharePoint reports viewers per item. Someone who reads three pages counts as three viewers, so these figures compare well against each other but are not a headcount.",
        hourly: "Hourly data is only available on tenants that answer the hourly interval; the chart is empty otherwise.",
        devices: "Device breakdown is not exposed by the site analytics endpoints, so it is not reported here rather than being guessed at.",
    },
    empty: {
        title: "No analytics yet",
        description: "Run the audit to read view counts for every page and file on this site.",
        entries: "Nothing was measured. Check the page and library limits.",
        unviewed: "Every page has been viewed at least once in this window.",
    },
    review: "Review",
};
//# sourceMappingURL=AnalyticsAudit.content.js.map