export const SettingsContent = {
    title: "Settings",
    description: "Settings are edited here and stored as JSON on the web part. The property pane only exposes the raw JSON.",
    readOnlyNotice: "The page is in read mode, so settings cannot be saved. Switch to edit mode to change them.",
    enterEditMode: "Enter edit mode",
    unsavedNotice: "Settings applied. Save the page to keep them.",
    save: "Apply settings",
    reset: "Reset changes",
    branding: "Branding",
    reports: "Report storage",
    sites: "Sites in scope",
    performance: "Performance",
    fields: {
        appName: "App name",
        appTagline: "Tagline",
        reportLibrary: "Library",
        reportFolder: "Folder",
        path: "Full path",
        concurrency: "Parallel requests",
        defaultRoute: "Landing page",
        captureReportLogs: "Capture report logs",
        captureReportLogsHint: "Keeps a run log on each report for debugging. Turn off to keep reports small.",
        additionalSites: "Additional site URLs",
        additionalSitesHint: "One absolute URL per line. The host site is always included.",
    },
    folder: {
        title: "Report folder",
        ensure: "Create or repair folder",
        check: "Re-check",
        exists: "Folder ready",
        missing: "Folder missing",
        noEdit: "You can view this folder but not write to it",
        noView: "No access to this location",
        checking: "Checking folder…",
        permissions: "Permissions",
        view: "View",
        edit: "Edit",
    },
    throttle: {
        title: "Live request state",
        inFlight: "In flight",
        queued: "Queued",
        completed: "Completed",
        retries: "Retries",
        failed: "Failed",
        pause: "Pause requests",
        resume: "Resume requests",
    },
    configWarning: "Modules stay disabled until these settings are complete:",
    modules: {
        title: "Modules",
        description: "Switch off anything this site does not need. A module switched off here is hidden from the sidebar, the dashboard and routing; its saved reports stay readable.",
        hostLimited: "The page hosting this app offers only the modules listed here.",
        enableAll: "Enable all",
        disableAll: "Disable all",
        enabled: "On",
        disabled: "Off",
    },
    host: "Host site",
    additional: "Additional site",
};
//# sourceMappingURL=Settings.content.js.map