export const ListsAuditContent = {
  title: "Lists and libraries",
  description:
    "Inventory of every list and library on the selected sites: item counts, storage, versioning, permissions and staleness.",
  run: "Run audit",
  rerun: "Run again",
  resume: "Resume",
  pause: "Pause",
  cancel: "Cancel",
  loadSaved: "Load saved report",
  exportCsv: "Export CSV",
  searchLists: "Search lists",
  details: "Details",
  tileInfo: {
    lists: "Visible lists that are not document libraries.",
    libraries: "Visible document libraries, including Site Pages and Site Assets.",
    items: "Item count reported by SharePoint for visible lists, folders included.",
    folders: "Folders counted while scanning items. Deep folder trees slow browsing and sync.",
    files: "Files counted while scanning libraries.",
    contentTypes: "Distinct visible content types attached across all scanned lists.",
    storage: "Total size of the files counted during the scan.",
    stale: "Lists with no item changed inside the stale window set for this run.",
    empty: "Lists holding no items at all.",
    governance: "Lists with versioning off or unique permissions.",
  },
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  backToRuns: "All runs",
  moduleVersion: "Module",
  review: "Review",
  staleLabel: "Stale",
  activeLabel: "Active",
  storageUnavailable:
    "Storage metrics were not returned for these lists. The tenant may block StorageMetrics, or the audit ran with storage measurement off.",
  storageUnavailableShort: "Storage unavailable",
  tabs: {
    overview: "Overview",
    lists: "All lists",
    risks: "Governance",
    logs: "Log",
    issues: "Issues",
  },
  stats: {
    lists: "Lists",
    libraries: "Libraries",
    items: "Items",
    files: "Files",
    folders: "Folders",
    storage: "Storage",
    contentTypes: "Content types",
    stale: "Stale",
    empty: "Empty",
    governance: "Governance flags",
  },
  charts: {
    byTemplate: "Lists by template",
    split: "Lists by visibility",
    largestItems: "Items by list",
    largest: "Storage by list",
    contentTypes: "Lists by content type",
    extensions: "Files by type",
    extensionSize: "Storage by file type",
    governance: "Lists by governance flag",
  },
  columns: {
    actions: "Actions",
    folders: "Folders",
    files: "Files",
    contentTypes: "Content types",
    visibility: "Visibility",
    title: "Name",
    template: "Template",
    items: "Items",
    storage: "Storage",
    modified: "Last item modified",
    versioning: "Versioning",
    permissions: "Permissions",
  },
  empty: {
    title: "No audit yet",
    description: "Run the audit to inventory every list and library on the configured sites.",
  },
  risksEmpty: {
    title: "No governance risks",
    description: "Every list has versioning on and inherits permissions.",
  },
  issuesEmpty: {
    title: "No issues recorded",
    description: "Pages and lists that returned 401, 403 or 429 during the scan appear here.",
  },
  openSettings: "List settings",
  openList: "Open list",
  hidden: "Hidden",
  visible: "Visible",
  truncated: "item scan hit the per list cap on some lists, so counts and sizes are partial.",
  scanOff: "Item scanning was off for this run, so folder, file and size counts are unavailable.",
  dialog: {
    close: "Close",
    created: "Created",
    versionLimit: "Version limit",
    unlimited: "Unlimited",
    contentTypesOn: "Content types enabled",
    noContentTypes: "No visible content types were returned for this list.",
    noFiles: "No files were counted in this list.",
    scanTitle: "Scan coverage",
    itemsScanned: "items scanned",
    capped: "(hit the per list cap, so counts are partial)",
    notScanned: "Item scanning was off for this run.",
    perFile: "per file",
    daysAgo: "days ago",
    tabSummary: "Summary",
    tabConfiguration: "Configuration",
    tabFiles: "Files",
    filesOnlyTitle: "Lists do not hold files",
    filesOnly: "File type and storage breakdowns only apply to document libraries.",
    url: "Server relative URL",
  },
  cardInfo: {
    templates: "How many lists use each list template. Useful for spotting duplicated or legacy list types.",
    contentTypes: "How often each content type is attached to a list. A long tail usually means content type sprawl.",
    extensions: "File extensions counted across every scanned library.",
    extensionSize: "Storage used by each file type, so you can see what is actually consuming space.",
    largest: "Libraries and lists holding the most storage.",
    largestItems: "Lists holding the most items. Very large lists are the ones that hit list view thresholds.",
    split: "Split of visible libraries, visible lists and hidden or system lists.",
    governance: "Versioning and permission flags across visible lists.",
    listContentTypes: "Content types attached to this list, with items spread evenly as an indication only.",
    listContentTypesFooter: "Even split, SharePoint does not report items per content type without scanning each item.",
  },
  governanceIntro:
    "Lists flagged here are worth a look before they cause problems: versioning off means an accidental overwrite cannot be undone, and unique permissions mean the list no longer follows site access.",
  unique: "Unique",
  inherited: "Inherited",
  on: "On",
  off: "Off",
} as const;
