export const ImagesAuditContent = {
    title: "Images",
    description: "Every image the site stores and every image its content points at: formats, sizes, duplicates, files nobody uses, missing alt text and images loaded from other hosts.",
    configTitle: "Audit settings",
    historyTitle: "Previous runs",
    moduleVersion: "Module",
    backToRuns: "All runs",
    run: "Run audit",
    rerun: "Run again",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    exportCsv: "Export CSV",
    review: "Review",
    tabs: { overview: "Overview", files: "Files", usages: "Usages", duplicates: "Duplicates", unused: "Unused" },
    stats: {
        files: "Image files",
        storage: "Image storage",
        average: "Average size",
        usages: "Image placements",
        used: "Files in use",
        unused: "Unused files",
        unusedBytes: "Unused storage",
        duplicates: "Duplicate files",
        duplicateBytes: "Duplicate storage",
        alt: "Placements without alt text",
        external: "Images from other hosts",
        oversized: "Oversized files",
        legacy: "Legacy formats",
        formats: "Formats in use",
    },
    tileInfo: {
        files: "Image files found in the libraries that were scanned.",
        storage: "Total size of those files.",
        average: "Mean file size, useful for spotting a library full of camera originals.",
        usages: "Image tags found in page canvases and rich text columns.",
        used: "Files matched to at least one placement.",
        unused: "Files no scanned content points at. Check before deleting, since other sites may use them.",
        unusedBytes: "Storage held by files nothing points at.",
        duplicates: "Files sharing a name and size with another file, so the same picture is stored twice.",
        duplicateBytes: "Storage that duplicates hold.",
        alt: "Image placements with no alt text. Each is a WCAG 1.1.1 failure for screen reader users.",
        external: "Images loaded from a host outside this tenant, which can break or leak referrers.",
        oversized: "Files over the size threshold set for this run.",
        legacy: "Formats the web handles poorly: bmp, tiff and ico.",
        formats: "Distinct file extensions found.",
    },
    charts: {
        format: "Files by format",
        storageFormat: "Storage by format",
        usage: "Placements by page",
        alt: "Placements by alt text",
        size: "Files by size",
        used: "Files by use",
    },
    cardInfo: {
        format: "Which image formats the site stores. Modern formats compress far better.",
        storageFormat: "Where the image storage actually goes.",
        usage: "Pages and items carrying the most images.",
        alt: "Placements with alt text against those missing it.",
        size: "File sizes bucketed, so heavy originals stand out.",
        used: "Files matched to content against files nothing points at.",
    },
    columns: {
        name: "File",
        list: "Library",
        format: "Format",
        size: "Size",
        modified: "Modified",
        uses: "Uses",
        flags: "Flags",
        page: "Used on",
        src: "Source",
        alt: "Alt text",
        dimensions: "Width and height",
        actions: "Actions",
        duplicateOf: "Duplicate key",
    },
    flags: {
        unused: "Unused",
        duplicate: "Duplicate",
        oversized: "Oversized",
        legacy: "Legacy format",
        missingAlt: "No alt text",
        external: "External host",
    },
    buckets: { small: "Under 100 KB", medium: "100 KB to 500 KB", large: "500 KB to 2 MB", huge: "Over 2 MB" },
    used: "In use",
    unused: "Unused",
    withAlt: "With alt text",
    withoutAlt: "Missing alt text",
    open: "Open",
    matchNote: "Usage matching compares the file path to the image source, so images referenced from another site collection or by an absolute CDN URL count as external rather than used.",
    empty: { title: "No audit yet", description: "Run the audit to inventory image files and where they are used." },
    noDuplicates: { title: "No duplicates", description: "No two files share a name and size." },
    noUnused: { title: "Everything is used", description: "Every image file was matched to at least one placement." },
    search: { files: "Search files", usages: "Search placements" },
};
//# sourceMappingURL=ImagesAudit.content.js.map