export const PermissionsAuditContent = {
  title: "Permissions",
  description:
    "Who can reach this site and how: SharePoint groups and their members, the permission levels in use, every role assignment, where inheritance is broken, and grants made straight to a person rather than through a group.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  moduleVersion: "Module",
  backToRuns: "All runs",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  review: "Review",
  tabs: {
    overview: "Overview",
    groups: "Groups",
    levels: "Permission levels",
    grants: "Grants",
    unique: "Broken inheritance",
    items: "Item breaks",
  },
  stats: {
    groups: "Groups",
    members: "Group members",
    empty: "Empty groups",
    levels: "Permission levels",
    custom: "Custom levels",
    grants: "Role assignments",
    direct: "Direct user grants",
    external: "External principals",
    everyone: "Everyone grants",
    sharing: "Sharing link groups",
    unique: "Lists with unique permissions",
    itemBreaks: "Sampled items with unique permissions",
    fullControl: "Full control grants",
  },
  tileInfo: {
    groups: "SharePoint groups defined on this site collection.",
    members: "Total membership across those groups, counting a person once per group.",
    empty: "Groups with no members. Usually leftovers, and confusing when picking a group to use.",
    levels: "Permission levels available on the site.",
    custom: "Levels that are not one of the built in roles, so someone created or edited them.",
    grants: "Every role assignment found on the web and on lists with unique permissions.",
    direct: "Permissions given straight to a person instead of through a group. These are the hardest to maintain.",
    external: "Guest accounts holding permissions, identified by their login name.",
    everyone: "Grants to Everyone or Everyone except external users, which open content to the whole tenant.",
    sharing: "System groups created by sharing links. Many of these means a lot of ad hoc sharing.",
    unique: "Lists that no longer inherit permissions from the site.",
    itemBreaks: "Items in the sample that carry their own permissions.",
    fullControl: "Assignments that include Full Control.",
  },
  charts: {
    kind: "Grants by principal type",
    level: "Grants by permission level",
    members: "Members by group",
    inheritance: "Lists by inheritance",
  },
  cardInfo: {
    kind: "Users, SharePoint groups and directory groups holding permissions. Direct users are the ones to reduce.",
    level: "Which permission levels are actually handed out, and how often.",
    members: "Group sizes, so oversized or empty groups stand out.",
    inheritance: "Lists inheriting site permissions against lists managing their own.",
  },
  columns: {
    group: "Group",
    owner: "Owner",
    members: "Members",
    membership: "Membership",
    level: "Permission level",
    type: "Type",
    builtIn: "Built in",
    custom: "Custom",
    description: "Description",
    principal: "Principal",
    kind: "Type",
    scope: "Scope",
    scopeType: "Scope type",
    roles: "Permission levels",
    flags: "Flags",
    list: "List",
    template: "Template",
    items: "Items",
    sampled: "Sampled",
    broken: "Items with unique permissions",
    actions: "Actions",
    item: "Item",
  },
  kinds: {
    user: "User",
    sharePointGroup: "SharePoint group",
    securityGroup: "Security group",
    distributionList: "Distribution list",
    other: "Other",
  },
  flags: {
    external: "External",
    everyone: "Everyone",
    sharing: "Sharing link",
    fullControl: "Full control",
    siteAdmin: "Site admin",
  },
  scope: { web: "Site", list: "List" },
  level: {
    rights: "Rights included",
    holders: "Who holds it",
    noRights: "No individual rights were returned for this level.",
    noHolders: "Nothing in the scopes that were read uses this level.",
  },
  openItem: "Open item",
  noBrokenItems: "No item level breaks found",
  noBrokenItemsHint: "Every item read inherits permissions from its list.",
  itemsOffHint: "Turn on item sampling in the audit settings to find items that carry their own permissions.",
  membershipOpen: "Members can edit membership",
  membershipClosed: "Owners manage membership",
  directNotice:
    "Permissions given directly to people are easy to lose track of. Where you can, move these into a group and grant the group instead.",
  everyoneNotice: "One or more grants target Everyone. Check that the content is genuinely meant for the whole tenant.",
  empty: {
    title: "No audit yet",
    description: "Run the audit to read groups, permission levels and every role assignment on this site.",
  },
  search: {
    groups: "Search groups",
    levels: "Search levels",
    grants: "Search grants",
    unique: "Search lists",
    items: "Search items",
  },
  itemsOff: "Item level checks were off for this run.",
  openPermissions: "Open permissions",
} as const;
