export const SearchToolContent = {
    title: "Search",
    description: "Query the SharePoint search index directly: build a KQL query from filters or write your own, inspect the managed properties returned, and check whether an item is indexed.",
    moduleVersion: "Module",
    tabs: {
        search: "Search",
        index: "Index check",
        history: "History",
    },
    form: {
        title: "Query",
        keywords: "Keywords",
        keywordsHint: "Free text. Leave empty to match everything.",
        fileTypes: "File types",
        fileTypesHint: "Comma separated, for example docx,pdf",
        contentClass: "Content class",
        contentClassHint: "STS_ListItem, STS_Document, STS_Site, STS_Web",
        path: "Path starts with",
        author: "Author",
        modifiedAfter: "Modified after",
        modifiedBefore: "Modified before",
        extraKql: "Extra KQL",
        extraKqlHint: "Appended with AND, for example IsDocument:true",
        useRawQuery: "Write the query myself",
        rawQuery: "KQL query",
        queryTemplate: "Query template",
        sourceId: "Result source",
        selectProperties: "Managed properties to return",
        refiners: "Refiners",
        refinersHint: "Comma separated managed properties, for example FileType,contentclass",
        sortProperty: "Sort by",
        sortDescending: "Sort descending",
        rowLimit: "Rows per page",
        trimDuplicates: "Trim duplicates",
        enableStemming: "Enable stemming",
        run: "Run search",
        reset: "Reset",
        copyQuery: "Copy KQL",
        copied: "Copied",
        exportCsv: "Export CSV",
        preview: "Query sent to search",
        moreFilters: "More filters",
        moreFiltersHint: "Content class, author, dates, extra KQL",
        moreOptions: "Query options",
        moreOptionsHint: "Properties, refiners, sorting, source, ranking",
        xrankTerms: "XRANK boost terms",
        xrankBoost: "Boost (cb)",
        xrankHint: "Boosts results matching these terms without excluding anything else.",
    },
    results: {
        title: "Results",
        summary: "results",
        elapsed: "in",
        empty: {
            title: "No results",
            description: "Nothing in the index matched this query. Loosen the filters or check the path.",
        },
        idle: {
            title: "No search yet",
            description: "Build a query on the left, then run the search.",
        },
        next: "Next page",
        previous: "Previous page",
        page: "Page",
        refiners: "Refiners",
        refinersHint: "Narrow these results by a returned property",
        refinedBy: "Refined by",
        clearRefiners: "Clear refinements",
        failed: "The search request failed. The detail below comes straight from SharePoint.",
        open: "Open item",
        details: "Details",
    },
    index: {
        title: "Is this item indexed?",
        description: "Paste a full URL or a server relative path. The check runs a Path query, which is how search itself resolves an item.",
        target: "Item URL or path",
        check: "Check index",
        indexed: "Found in the index",
        notIndexed: "Not found in the index",
        notIndexedHint: "A missing item usually means it was changed very recently, is in a library excluded from search, or the crawl has not run yet.",
        lastModified: "Last modified",
        fileType: "File type",
        contentClass: "Content class",
        web: "Site",
        queryUsed: "Query used",
        mode: "Choose the item",
        modeUrl: "Paste a URL",
        modeList: "Pick from a list",
        list: "List",
        listPlaceholder: "Type to find a list",
        item: "Item",
        itemPlaceholder: "Type to find an item",
        loadingLists: "Loading lists",
        loadingItems: "Loading items",
        checkTime: "Check time",
        failed: "The index check failed",
    },
    history: {
        title: "Recent queries",
        empty: { title: "No queries yet", description: "Searches you run are listed here for this browser." },
        rerun: "Run again",
        clear: "Clear history",
        when: "When",
        query: "Query",
        rows: "Rows",
        time: "Time",
    },
    sourceIds: {
        default: "Default",
        documents: "Local SharePoint documents",
        items: "Local SharePoint items",
        pages: "Pages",
        people: "Local people",
    },
};
//# sourceMappingURL=SearchTool.content.js.map