import * as React from "react";
import { Tokens } from "@/theme/Tokens";

export const AppStyles = {
  shell: (fullscreen: boolean): React.CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: "100%",
    background: Tokens.colour.bg,
    color: Tokens.colour.text,
    fontFamily: Tokens.font.family,
    fontSize: Tokens.font.md,
    ...(fullscreen
      ? {
          position: "fixed",
          inset: 0,
          zIndex: Tokens.zIndex.fullscreen,
          height: "100vh",
        }
      : {
          position: "relative",
          minHeight: 560,
          border: `1px solid ${Tokens.colour.border}`,
          borderRadius: Tokens.radius.lg,
          overflow: "hidden",
        }),
  }),
  topbar: {
    display: "flex",
    alignItems: "center",
    gap: Tokens.space.md,
    padding: `0 ${Tokens.space.md}`,
    height: 56,
    flex: "0 0 auto",
    background: Tokens.colour.surface,
    borderBottom: `1px solid ${Tokens.colour.border}`,
    zIndex: Tokens.zIndex.topbar,
  } as React.CSSProperties,
  body: {
    display: "flex",
    flex: "1 1 auto",
    minHeight: 0,
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
  } as React.CSSProperties,
  sidebar: (open: boolean): React.CSSProperties => ({
    width: open ? 248 : 0,
    flex: "0 0 auto",
    background: Tokens.colour.surface,
    borderRight: open ? `1px solid ${Tokens.colour.border}` : "none",
    overflowY: "auto",
    overflowX: "hidden",
    transition: "width 160ms ease",
    zIndex: Tokens.zIndex.sidebar,
  }),
  main: {
    flex: "1 1 auto",
    minWidth: 0,
    maxWidth: "100%",
    overflowY: "auto",
    overflowX: "hidden",
    padding: Tokens.space.lg,
  } as React.CSSProperties,
  navGroupLabel: {
    padding: `${Tokens.space.md} ${Tokens.space.md} ${Tokens.space.xs}`,
    fontSize: Tokens.font.sm,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: Tokens.colour.textMuted,
  } as React.CSSProperties,
  navItem: (active: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: Tokens.space.sm,
    width: "100%",
    minHeight: Tokens.hitTarget,
    padding: `0 ${Tokens.space.md}`,
    border: "none",
    borderLeft: `3px solid ${active ? Tokens.colour.accent : "transparent"}`,
    background: active ? Tokens.colour.accentSoft : "transparent",
    color: active ? Tokens.colour.accent : Tokens.colour.text,
    font: "inherit",
    fontWeight: active ? 600 : 400,
    textAlign: "left",
    cursor: "pointer",
  }),
  footer: {
    padding: Tokens.space.md,
    fontSize: Tokens.font.sm,
    color: Tokens.colour.textMuted,
    borderTop: `1px solid ${Tokens.colour.border}`,
  } as React.CSSProperties,
};
