export const WebPartAuditContent = {
  title: "Web parts",
  description:
    "Reads the canvas of every page and extracts the web parts in use, where they sit, and the properties they were saved with.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  backToRuns: "All runs",
  moduleVersion: "Module",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  viewProperties: "Properties",
  searchInstances: "Search web parts, pages and titles",
  searchTypes: "Search web parts",
  searchPages: "Search pages",
  titled: "Titled",
  untitled: "No title",
  density: {
    empty: "Empty",
    light: "1 to 5",
    medium: "6 to 15",
    heavy: "16 or more",
  },
  tabs: {
    overview: "Overview",
    types: "Web part types",
    instances: "Instances",
    pages: "Pages",
    catalogue: "Installed, unused",
    logs: "Log",
    issues: "Issues",
  },
  stats: {
    pages: "Pages scanned",
    instances: "Web parts placed",
    types: "Distinct types",
    thirdParty: "Custom or third party",
    average: "Average per page",
    empty: "Pages with no web parts",
    text: "Stock text blocks",
  },
  charts: {
    topTypes: "Instances by web part",
    source: "Web parts by source",
    layouts: "Pages by layout",
    busiest: "Web parts by page",
    instanceSource: "Instances by source",
  },
  tileInfo: {
    pages: "Pages read from the Site Pages library on the scanned sites.",
    instances: "Every web part placed on those pages, title area included when that option was on.",
    types: "Distinct web parts and stock controls in use.",
    thirdParty: "Web parts that are not stock controls, worth checking for support and ownership.",
    average: "Web parts per page, a rough measure of page complexity.",
    empty: "Pages with no web parts at all, often stubs or redirects.",
    text: "Rich text blocks placed directly on the canvas rather than a web part.",
  },
  cardInfo: {
    topTypes: "How many times each web part is placed across the scanned pages.",
    source: "Split of stock controls, catalogue web parts and anything not installed on this site.",
    layouts: "Page layout used by the scanned pages, for example Article or Home.",
    busiest: "Pages carrying the most web parts. Heavy pages are the usual performance suspects.",
    instanceSource: "Every placement counted by source, so a single custom web part used 40 times shows its real weight.",
  },
  columns: {
    actions: "Actions",
    hasTitle: "Title set",
    density: "Density",
    icon: "",
    group: "Group",
    common: "Common properties",
    shared: "Shared values",
    catalogue: "Catalogue",
    name: "Web part",
    id: "Component id",
    instances: "Instances",
    pages: "Pages",
    source: "Source",
    properties: "Properties",
    page: "Page",
    section: "Section",
    title: "Instance title",
    layout: "Layout",
    count: "Web parts",
    sections: "Sections",
    modified: "Modified",
  },
  inCatalogue: "Installed",
  notInCatalogue: "Not installed",
  catalogueEmpty: {
    title: "Every installed web part is in use",
    description: "No component in the catalogue is missing from the scanned pages.",
  },
  none: "None",
  dialog: {
    close: "Close",
    property: "Property",
    usedOn: "Used on",
    commonValues: "Most common values",
    propertyUsage: "Property usage across the site",
    sharedValues: "Values identical on every instance",
    noShared: "No property has the same value on every instance.",
    whereUsed: "Where it is used",
    commonProperties: "Common properties",
    openPage: "Open page",
    hideProperties: "Hide properties",
    viewDetails: "Details",
  },
  outOfBox: "Out of the box",
  thirdParty: "Custom",
  text: "Text or layout",
  titleArea: "Title area",
  body: "Body",
  empty: {
    title: "No audit yet",
    description: "Run the audit to read every page canvas and extract the web parts in use.",
  },
  issuesEmpty: {
    title: "No issues recorded",
    description: "Pages that could not be read or parsed appear here.",
  },
  propertiesTitle: "Saved properties",
  noProperties: "This instance has no saved properties, or properties were not kept for this run.",
} as const;
