export const PublishingAuditContent = {
  title: "Publishing",
  description:
    "What has been published, by whom and when: approval status, edit and creation frequency, version depth, review and expiry dates, and content nobody has touched or opened for a long time.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  moduleVersion: "Module",
  backToRuns: "All runs",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  review: "Review",
  people: {
    title: "People",
    description: "Everyone who created or last edited something in this scan.",
    empty: "No creators or editors were recorded for the scanned items.",
    columns: {
      name: "Person",
      created: "Created",
      edited: "Last editor of",
      touched: "Items",
      unpublished: "Unpublished",
      stale: "Stale",
      lists: "Lists",
      lastEdit: "Last edit",
    },
    dialog: {
      items: "Everything they touched",
      stats: "Their share of the scan",
    },
  },
  unpublishedTab: "Unpublished",
  unpublishedEmpty: "Everything scanned has a published version.",
  tabs: {
    overview: "Overview",
    items: "Items",
    review: "Review dates",
    stale: "Stale",
    people: "People",
    unpublished: "Unpublished",
  },
  stats: {
    items: "Items read",
    approved: "Approved",
    pending: "Pending approval",
    draft: "Draft",
    rejected: "Rejected",
    created: "Created in window",
    modified: "Modified in window",
    stale: "Stale",
    never: "Never edited",
    due: "Past review date",
    expired: "Past expiry date",
    versions: "Average versions",
    maxVersions: "Deepest version history",
    editors: "Distinct editors",
    authors: "Creators",
    unpublished: "Unpublished",
    versionsScanned: "Versions scanned",
    lists: "Lists read",
  },
  tileInfo: {
    items: "Items read across the lists in scope, newest changes first.",
    approved: "Items whose moderation status is approved. Lists without approval report everything as approved.",
    pending: "Items waiting for someone to approve them.",
    draft: "Items saved as a draft and never published.",
    rejected: "Items an approver rejected.",
    created: "Items created inside the timeframe set for this run.",
    modified: "Items changed inside the timeframe.",
    stale: "Items not modified inside the stale window.",
    never: "Items whose modified date matches their created date, so nobody has edited them since.",
    due: "Items with a review date in the past.",
    expired: "Items with an expiry date in the past.",
    versions: "Mean version count across the sampled items.",
    maxVersions: "The deepest version history found, which is where storage tends to hide.",
    editors: "People who last edited at least one item.",
    authors: "Distinct people who created something in the scan.",
    unpublished: "Items with no published version: held by moderation, or sitting on a 0.x draft version.",
    versionsScanned: "Total versions read across the sampled items.",
    lists: "Lists and libraries included in this run.",
  },
  charts: {
    created: "Items created by month",
    modified: "Items modified by month",
    weekday: "Edits by weekday",
    status: "Items by approval status",
    editors: "Items by last editor",
    staleness: "Items by age since edit",
    list: "Items by list",
  },
  cardInfo: {
    created: "When content was added, month by month.",
    modified: "When content was last touched, month by month.",
    weekday: "Which days edits land on, which says a lot about how a site is maintained.",
    status: "Approval state across everything read.",
    editors: "Who last touched the most items.",
    staleness: "How long since each item was edited, bucketed.",
    list: "Where the items read actually live.",
  },
  columns: {
    title: "Item",
    list: "List",
    status: "Status",
    author: "Created by",
    editor: "Last edited by",
    created: "Created",
    modified: "Modified",
    age: "Age since edit",
    version: "Version",
    versions: "Versions",
    review: "Review date",
    expiry: "Expiry date",
    actions: "Actions",
  },
  status: {
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    draft: "Draft",
    scheduled: "Scheduled",
    unknown: "No approval",
  },
  buckets: {
    month: "Under a month",
    quarter: "1 to 3 months",
    year: "3 to 12 months",
    older: "Over a year",
  },
  open: "Open",
  dialog: {
    dates: "Date columns",
    noDates: "No configured date column has a value on this item.",
    versions: "Version history",
    loadVersions: "Load version history",
    versionsRead: "versions read, most recent first",
  },
  versionsNote: "Version counts come from a sample of the most recently changed items.",
  empty: { title: "No audit yet", description: "Run the audit to read publishing state and edit history." },
  noReview: {
    title: "No review or expiry dates",
    description: "None of the items read carry the date columns configured for this run.",
  },
  noStale: { title: "Nothing stale", description: "Every item was edited inside the stale window." },
  search: "Search items",
} as const;
