export const ContentAuditContent = {
  title: "Content",
  description:
    "How much writing lives on this site and how it is put together: word counts, headings, images and their alt text, links, tables and embeds, across page canvases and rich text columns.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  moduleVersion: "Module",
  backToRuns: "All runs",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  review: "Review",
  tabs: { overview: "Overview", entries: "Content", issues: "Issues" },
  stats: {
    entries: "Content blocks",
    pages: "Pages",
    items: "List items",
    words: "Words",
    average: "Average words",
    averageReading: "Average reading time",
    reading: "Reading time",
    headings: "Headings",
    images: "Images",
    links: "Links",
    external: "External links",
    empty: "Empty links",
    tables: "Tables",
    embeds: "Embeds",
    thin: "Thin content",
    noHeadings: "No headings",
  },
  tileInfo: {
    entries: "Each page canvas and each rich text column value counts as one block.",
    pages: "Modern pages read from the Site Pages library.",
    items: "List items carrying rich text, such as an event description.",
    words: "Words across every block measured.",
    average: "Mean words per block.",
    averageReading: "Mean reading time per block at 220 words a minute.",
    reading: "Rough reading time at 220 words a minute.",
    headings: "Heading elements found, across all levels.",
    images: "Image elements found in the content.",
    links: "Anchor elements found.",
    external: "Links pointing at another host.",
    empty: "Links with no destination, a hash, or javascript, which usually means broken markup.",
    tables: "Table elements, worth checking for header rows.",
    embeds: "Iframes, videos and embeds.",
    thin: "Blocks under the word count set for this run.",
    noHeadings: "Blocks with body text but no heading, which are hard to scan and skim.",
  },
  charts: {
    words: "Words by page",
    headings: "Headings by level",
    contentType: "Blocks by content type",
    list: "Words by list",
    source: "Blocks by source",
  },
  cardInfo: {
    words: "The longest content on the site, which is usually where reviews should start.",
    headings: "Heading levels in use. A healthy page leads with one h1 or h2 then nests.",
    contentType: "Content types behind the blocks measured.",
    list: "Where the words live, by list.",
    source: "Where the content lives: page canvases against rich text columns on lists.",
  },
  columns: {
    title: "Content",
    source: "Source",
    list: "List",
    column: "Column",
    words: "Words",
    reading: "Reading",
    headings: "Headings",
    images: "Images",
    links: "Links",
    tables: "Tables",
    modified: "Modified",
    issues: "Issues",
    actions: "Actions",
  },
  sources: { page: "Page", item: "List item" },
  issues: {
    thin: "Thin",
    noHeadings: "No headings",
    emptyLinks: "Empty links",
    none: "None",
  },
  open: "Open",
  dialog: {
    metrics: "Measurements",
    headings: "Heading structure",
    noHeadings: "No headings were found in this block.",
  },
  empty: {
    title: "No audit yet",
    description: "Run the audit to measure page content and rich text columns.",
  },
  noIssues: {
    title: "Nothing flagged",
    description: "No block is thin, missing headings, missing alt text or carrying empty links.",
  },
  search: "Search content",
} as const;
