export const LinkAuditContent = {
  title: "Link audit",
  description:
    "Finds every link written on a page, in a list item, in a navigation menu or inside a document, resolves what each one points at, and reports what is broken, legacy, external or insecure.",
  moduleVersion: "Version",
  historyTitle: "Previous link audits",
  backToRuns: "Back to runs",
  configTitle: "Link audit settings",
  run: "Run link audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",

  exportCsv: "Export link audit",
  exportExternal: "Export external only",
  exportBroken: "Export broken only",
  exportReferences: "Export items",
  exportLinks: "Export links",
  exportUsages: "Export usages",
  openLink: "Open link",
  openItem: "Open item",

  tabs: {
    overview: "Overview",
    references: "Items",
    links: "Links",
    broken: "Broken",
  },

  search: {
    references: "Search items, urls and links",
    links: "Search links, text and targets",
    broken: "Search broken links",
  },

  columns: {
    list: "List",
    title: "Title",
    kind: "Kind",
    incoming: "Incoming",
    outgoing: "Outgoing",
    broken: "Broken",
    link: "Link",
    source: "Source",
    foundIn: "Found in",
    type: "Type",
    status: "Status",
    uses: "Uses",
    spellings: "Spellings",
    resolvesTo: "Resolves to",
    text: "Text",
    url: "URL",
    item: "Item",
    id: "ID",
    usedIn: "Used in",
    modified: "Modified",
    flags: "Flags",
  },

  stats: {
    items: "Items",
    pages: "Pages",
    listItems: "List items",
    documents: "Documents",
    pdfs: "PDFs",
    docx: "Word docs",
    scanned: "Scanned",
    documentsRead: "Files read",
    outgoing: "Outgoing links",
    incoming: "Incoming links",
    destinations: "Destinations",
    webpart: "In web parts",
    navigation: "In navigation",
    documentLinks: "In documents",
    external: "External",
    broken: "Broken",
    untested: "Untested",
    orphans: "Nothing links here",
  },

  tileInfo: {
    items: "Everything scanned: pages, list items, documents and the navigation menus.",
    pages: "Site pages read from the Site Pages library.",
    listItems: "List items carrying rich text columns.",
    documents: "Files inventoried in document libraries.",
    pdfs: "PDF files found in libraries.",
    docx: "Word files found in libraries.",
    scanned: "Items whose content was read for links.",
    documentsRead: "Documents whose file content was parsed for links.",
    outgoing: "Every link found, counted once per placement.",
    incoming: "Links resolved back to a scanned item.",
    destinations: "Distinct destinations once every spelling of a url is collapsed.",
    webpart: "Links saved in web part properties rather than body text.",
    navigation: "Links held in the quick launch and top navigation menus.",
    documentLinks: "Links read out of docx and pdf file content.",
    external: "Links pointing off this tenancy. They cannot be tested from the browser.",
    broken: "Links proven dead, either legacy or answered with an error status.",
    untested: "Links that could not be proven either way.",
    orphans: "Scanned items that nothing else links to.",
  },

  charts: {
    type: "Links by type",
    source: "Links by where they were written",
    status: "Links by status",
    brokenByList: "Broken links by list",
    topTargets: "Most linked destinations",
  },

  cardInfo: {
    type: "Classification of every link found, first match wins.",
    source: "Body content, web part properties, navigation menus or document files.",
    status: "Broken, working or untested after the index and the broken link check.",
    brokenByList: "Where the dead links are written, so the fixing can be handed out.",
    topTargets: "Destinations by how many places link to them.",
  },

  status: {
    yes: "Broken",
    no: "Working",
    unsure: "Untested",
    matched: "Matched",
    unmapped: "Unmapped",
  },

  sources: {
    content: "Content",
    webpart: "Web part",
    navigation: "Navigation",
    document: "Document",
  },

  kinds: {
    page: "Page",
    item: "List item",
    document: "Document",
    navigation: "Navigation",
  },

  navigationTitle: "Navigation menus",
  navigationList: "Navigation",

  notes: {
    external: "External links cannot be tested from the browser, so they stay untested however often they are checked.",
    documents: "Document content is downloaded and parsed in the browser, two files at a time, and files over the size limit are skipped.",
    broken: "Only unresolved links on this tenancy are requested. Everything that matched a scanned item is already known good.",
  },

  empty: {
    title: "No link audit yet",
    description: "Run the audit to read every page, list item, menu and document, then resolve what each link points at.",
    references: "Nothing was scanned. Check the site list and the page and item limits.",
    links: "No links were found in anything that was scanned.",
    broken: "No broken links. Nothing pointed at a legacy host and nothing answered with an error.",
  },

  flags: {
    broken: "Broken links",
    legacy: "Legacy",
    insecure: "Insecure",
    emptyText: "No link text",
    unmapped: "Unmapped",
    orphan: "No incoming",
  },

  dialog: {
    outgoing: "Outgoing links",
    incoming: "Incoming links",
    brokenLinks: "Broken links",
    variants: "Written as",
    usedIn: "Linked from",
    noBroken: "No broken links on this item.",
    noOutgoing: "This item links to nothing.",
    noIncoming: "Nothing links to this item.",
  },

  review: "Review",
} as const;
