export declare const LinkAuditContent: {
    readonly title: "Link audit";
    readonly description: "Finds every link written on a page, in a list item, in a navigation menu or inside a document, resolves what each one points at, and reports what is broken, legacy, external or insecure.";
    readonly moduleVersion: "Version";
    readonly historyTitle: "Previous link audits";
    readonly backToRuns: "Back to runs";
    readonly configTitle: "Link audit settings";
    readonly run: "Run link audit";
    readonly rerun: "Run again";
    readonly pause: "Pause";
    readonly resume: "Resume";
    readonly cancel: "Cancel";
    readonly exportCsv: "Export link audit";
    readonly exportExternal: "Export external only";
    readonly exportBroken: "Export broken only";
    readonly exportReferences: "Export items";
    readonly exportLinks: "Export links";
    readonly exportUsages: "Export usages";
    readonly openLink: "Open link";
    readonly openItem: "Open item";
    readonly tabs: {
        readonly overview: "Overview";
        readonly references: "Items";
        readonly links: "Links";
        readonly broken: "Broken";
        readonly external: "External";
        readonly megaMenu: "Mega menu";
        readonly actions: "Actions";
    };
    readonly search: {
        readonly references: "Search items, urls and links";
        readonly links: "Search links, text and targets";
        readonly broken: "Search broken links";
    };
    readonly columns: {
        readonly list: "List";
        readonly title: "Title";
        readonly kind: "Kind";
        readonly incoming: "Incoming";
        readonly outgoing: "Outgoing";
        readonly broken: "Broken";
        readonly link: "Link";
        readonly source: "Source";
        readonly foundIn: "Found in";
        readonly type: "Type";
        readonly status: "Status";
        readonly uses: "Uses";
        readonly spellings: "Spellings";
        readonly resolvesTo: "Resolves to";
        readonly text: "Text";
        readonly url: "URL";
        readonly item: "Item";
        readonly id: "ID";
        readonly usedIn: "Used in";
        readonly modified: "Modified";
        readonly flags: "Flags";
    };
    readonly sections: {
        readonly scanned: "What was scanned";
        readonly destinations: "Where links point";
        readonly written: "How links are written";
        readonly health: "Link health";
    };
    readonly stats: {
        readonly items: "Items";
        readonly pages: "Pages";
        readonly listItems: "List items";
        readonly documents: "Documents";
        readonly pdfs: "PDFs";
        readonly docx: "Word docs";
        readonly scanned: "Scanned";
        readonly documentsRead: "Files read";
        readonly outgoing: "Outgoing links";
        readonly incoming: "Incoming links";
        readonly destinations: "Destinations";
        readonly webpart: "In web parts";
        readonly navigation: "In navigation";
        readonly documentLinks: "In documents";
        readonly external: "External";
        readonly broken: "Broken";
        readonly untested: "Untested";
        readonly orphans: "No inbound links";
        readonly attachments: "Attachments";
        readonly attachmentLinks: "In attachments";
        readonly configFiles: "Config files";
        readonly configLinks: "In config files";
        readonly megaMenuLinks: "In mega menu";
        readonly thisSite: "This site";
        readonly otherSite: "Other site";
        readonly share: "Share links";
        readonly internal: "Internal";
        readonly relative: "Relative";
        readonly absolute: "Absolute";
        readonly displayForm: "To list items";
        readonly mapped: "Mapped";
        readonly unmapped: "Unmapped";
        readonly emptyText: "No link text";
        readonly contact: "Contact";
        readonly anchor: "Anchor";
        readonly newTab: "Open in new tab";
        readonly insecure: "Insecure";
        readonly legacy: "Legacy";
        readonly documentsLinked: "To documents";
        readonly checked: "Urls requested";
    };
    readonly tileInfo: {
        readonly items: "Everything scanned: pages, list items, documents and the navigation menus.";
        readonly pages: "Site pages read from the Site Pages library.";
        readonly listItems: "List items carrying rich text columns.";
        readonly documents: "Files inventoried in document libraries.";
        readonly pdfs: "PDF files found in libraries.";
        readonly docx: "Word files found in libraries.";
        readonly scanned: "Items whose content was read for links.";
        readonly documentsRead: "Documents whose file content was parsed for links.";
        readonly outgoing: "Every link found, counted once per placement.";
        readonly incoming: "Links from elsewhere that resolved to a scanned item, counted once per place they were written. Not the same as This site, which counts links written towards this site whether or not they found anything.";
        readonly destinations: "Distinct destinations once every spelling of a url is collapsed.";
        readonly webpart: "Links saved in web part properties rather than body text.";
        readonly navigation: "Links held in the quick launch and top navigation menus.";
        readonly documentLinks: "Links read out of docx and pdf file content.";
        readonly external: "Links pointing off this tenancy. They cannot be tested from the browser.";
        readonly broken: "Links proven dead, either legacy or answered with an error status.";
        readonly untested: "Links that could not be proven either way.";
        readonly orphans: "Scanned items that nothing else on the site points at. Often fine for a form or an archive, worth a look for a page.";
        readonly share: "Links created by the Share button. They carry a token rather than a path, so they cannot be matched to an item or tested.";
        readonly relative: "Links written as a path, such as /sites/intranet/page.aspx. They survive a rename of the tenant.";
        readonly absolute: "Links written with the full https address. They break if the host ever changes.";
        readonly displayForm: "Links to a list item's display form. These are matched back to the item itself.";
        readonly mapped: "Links into this site that were matched to a scanned item.";
        readonly unmapped: "Links into this site that matched nothing scanned: a typo, a deleted page, or something outside the scan limits.";
        readonly attachments: "List item attachments found while scanning.";
        readonly attachmentLinks: "Links read out of attachment file content.";
        readonly configFiles: "Configuration JSON files scanned for links.";
        readonly configLinks: "Links held in configuration files rather than content.";
        readonly megaMenuLinks: "Links held in the mega menu configuration.";
        readonly thisSite: "Links written towards the site being audited, resolved or not.";
        readonly otherSite: "Links to another site on this tenancy. Internal, but owned by someone else.";
        readonly internal: "Every link that stays on this tenancy, this site or another.";
        readonly emptyText: "Links with no text on them, which a screen reader announces as the url.";
        readonly contact: "mailto: and tel: links.";
        readonly anchor: "Links to a position on the same page.";
        readonly newTab: "Links written to open in a new tab.";
        readonly insecure: "Links written as http rather than https.";
        readonly legacy: "Links to a host recorded as retired, which are dead by definition.";
        readonly documentsLinked: "Links whose destination is a file rather than a page.";
        readonly checked: "Unresolved links on this tenancy that were actually requested during the run.";
    };
    readonly charts: {
        readonly type: "Link types";
        readonly source: "Where links are written";
        readonly status: "Link health";
        readonly brokenByList: "Broken links by list";
        readonly topTargets: "Most linked pages";
    };
    readonly cardInfo: {
        readonly type: "What each link points at, counted once per placement.";
        readonly source: "Body text, web part properties, menus, config files or file content.";
        readonly status: "Working, broken or untested once the index and the link check have run.";
        readonly brokenByList: "Where the dead links are written, so the fixing can be handed out.";
        readonly topTargets: "Destinations by how many places link to them.";
    };
    readonly status: {
        readonly yes: "Broken";
        readonly no: "Working";
        readonly unsure: "Untested";
        readonly matched: "Mapped";
        readonly unmapped: "Unmapped";
    };
    readonly sources: {
        readonly content: "Content";
        readonly webpart: "Web part";
        readonly navigation: "Navigation";
        readonly document: "Document";
        readonly attachment: "Attachment";
        readonly config: "Config file";
        readonly megamenu: "Mega menu";
    };
    readonly types: {
        readonly thisSite: "This site";
        readonly otherSite: "Other site";
        readonly share: "Share link";
        readonly legacy: "Legacy";
        readonly document: "Document";
        readonly external: "External";
        readonly anchor: "Anchor";
        readonly contact: "Contact";
        readonly script: "Script";
        readonly unknown: "Unknown";
    };
    readonly kinds: {
        readonly page: "Page";
        readonly item: "List item";
        readonly document: "Document";
        readonly navigation: "Navigation";
        readonly attachment: "Attachment";
        readonly config: "Config file";
        readonly megamenu: "Mega menu";
    };
    readonly navigationTitle: "Navigation menus";
    readonly navigationList: "Navigation";
    readonly configList: "Config files";
    readonly megaMenuList: "Mega menu";
    readonly notes: {
        readonly external: "External links cannot be tested from the browser, so they stay untested however often they are checked.";
        readonly documents: "Document content is downloaded and parsed in the browser, two files at a time, and files over the size limit are skipped.";
        readonly broken: "Only unresolved links on this tenancy are requested. Everything that matched a scanned item is already known good.";
    };
    readonly actions: {
        readonly title: "Exports";
        readonly description: "Everything the audit can hand to a spreadsheet. Each file opens on a summary block of the same counts shown on the overview.";
        readonly fullAudit: "One row per link found, across every item, menu, config file and document.";
        readonly external: "Only links leaving this tenancy, for a review of who you send people to.";
        readonly broken: "Only links proven dead: a retired host, or an error status from the server.";
        readonly references: "One row per scanned item with its incoming, outgoing and broken counts.";
        readonly disabled: "Nothing to export yet.";
    };
    readonly empty: {
        readonly title: "No link audit yet";
        readonly description: "Run the audit to read every page, list item, menu and document, then resolve what each link points at.";
        readonly references: "Nothing was scanned. Check the site list and the page and item limits.";
        readonly links: "No links were found in anything that was scanned.";
        readonly broken: "No broken links. Nothing pointed at a legacy host and nothing answered with an error.";
        readonly external: "No links leave this tenancy.";
        readonly megaMenu: "No mega menu configuration was scanned. Set its path in the run settings.";
    };
    readonly flags: {
        readonly broken: "Broken links";
        readonly legacy: "Legacy";
        readonly insecure: "Insecure";
        readonly emptyText: "No link text";
        readonly unmapped: "Unmapped";
        readonly orphan: "No incoming";
    };
    readonly dialog: {
        readonly outgoing: "Outgoing links";
        readonly incoming: "Incoming links";
        readonly brokenLinks: "Broken links";
        readonly variants: "Written as";
        readonly usedIn: "Linked from";
        readonly noBroken: "No broken links on this item.";
        readonly noOutgoing: "This item links to nothing.";
        readonly noIncoming: "Nothing links to this item.";
    };
    readonly review: "Review";
};
//# sourceMappingURL=LinkAudit.content.d.ts.map