export const LinkAuditContent = {
    title: "Link audit",
    description: "Finds every link written on a page, in a list item, in a navigation menu or inside a document, resolves what each one points at, and reports what is broken, legacy, external or insecure.",
    moduleVersion: "Version",
    historyTitle: "Previous link audits",
    backToRuns: "Back to runs",
    configTitle: "Link audit settings",
    run: "Run link audit",
    rerun: "Run again",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    exportCsv: "Export link audit",
    exportExternal: "Export external only",
    exportBroken: "Export broken only",
    exportReferences: "Export items",
    exportLinks: "Export links",
    exportUsages: "Export usages",
    openLink: "Open link",
    openItem: "Open item",
    tabs: {
        overview: "Overview",
        references: "Items",
        links: "Links",
        broken: "Broken",
        external: "External",
        megaMenu: "Mega menu",
        actions: "Actions",
    },
    search: {
        references: "Search items, urls and links",
        links: "Search links, text and targets",
        broken: "Search broken links",
    },
    columns: {
        list: "List",
        title: "Title",
        kind: "Kind",
        incoming: "Incoming",
        outgoing: "Outgoing",
        broken: "Broken",
        link: "Link",
        source: "Source",
        foundIn: "Found in",
        type: "Type",
        status: "Status",
        uses: "Uses",
        spellings: "Spellings",
        resolvesTo: "Resolves to",
        text: "Text",
        url: "URL",
        item: "Item",
        id: "ID",
        usedIn: "Used in",
        modified: "Modified",
        flags: "Flags",
    },
    sections: {
        scanned: "What was scanned",
        destinations: "Where links point",
        written: "How links are written",
        health: "Link health",
    },
    stats: {
        items: "Items",
        pages: "Pages",
        listItems: "List items",
        documents: "Documents",
        pdfs: "PDFs",
        docx: "Word docs",
        scanned: "Scanned",
        documentsRead: "Files read",
        outgoing: "Outgoing links",
        incoming: "Incoming links",
        destinations: "Destinations",
        webpart: "In web parts",
        navigation: "In navigation",
        documentLinks: "In documents",
        external: "External",
        broken: "Broken",
        untested: "Untested",
        orphans: "No inbound links",
        attachments: "Attachments",
        attachmentLinks: "In attachments",
        configFiles: "Config files",
        configLinks: "In config files",
        megaMenuLinks: "In mega menu",
        thisSite: "This site",
        otherSite: "Other site",
        share: "Share links",
        internal: "Internal",
        relative: "Relative",
        absolute: "Absolute",
        displayForm: "To list items",
        mapped: "Mapped",
        unmapped: "Unmapped",
        emptyText: "No link text",
        contact: "Contact",
        anchor: "Anchor",
        newTab: "Open in new tab",
        insecure: "Insecure",
        legacy: "Legacy",
        documentsLinked: "To documents",
        checked: "Urls requested",
    },
    tileInfo: {
        items: "Everything scanned: pages, list items, documents and the navigation menus.",
        pages: "Site pages read from the Site Pages library.",
        listItems: "List items carrying rich text columns.",
        documents: "Files inventoried in document libraries.",
        pdfs: "PDF files found in libraries.",
        docx: "Word files found in libraries.",
        scanned: "Items whose content was read for links.",
        documentsRead: "Documents whose file content was parsed for links.",
        outgoing: "Every link found, counted once per placement.",
        incoming: "Links from elsewhere that resolved to a scanned item, counted once per place they were written. Not the same as This site, which counts links written towards this site whether or not they found anything.",
        destinations: "Distinct destinations once every spelling of a url is collapsed.",
        webpart: "Links saved in web part properties rather than body text.",
        navigation: "Links held in the quick launch and top navigation menus.",
        documentLinks: "Links read out of docx and pdf file content.",
        external: "Links pointing off this tenancy. They cannot be tested from the browser.",
        broken: "Links proven dead, either legacy or answered with an error status.",
        untested: "Links that could not be proven either way.",
        orphans: "Scanned items that nothing else on the site points at. Often fine for a form or an archive, worth a look for a page.",
        share: "Links created by the Share button. They carry a token rather than a path, so they cannot be matched to an item or tested.",
        relative: "Links written as a path, such as /sites/intranet/page.aspx. They survive a rename of the tenant.",
        absolute: "Links written with the full https address. They break if the host ever changes.",
        displayForm: "Links to a list item's display form. These are matched back to the item itself.",
        mapped: "Links into this site that were matched to a scanned item.",
        unmapped: "Links into this site that matched nothing scanned: a typo, a deleted page, or something outside the scan limits.",
        attachments: "List item attachments found while scanning.",
        attachmentLinks: "Links read out of attachment file content.",
        configFiles: "Configuration JSON files scanned for links.",
        configLinks: "Links held in configuration files rather than content.",
        megaMenuLinks: "Links held in the mega menu configuration.",
        thisSite: "Links written towards the site being audited, resolved or not.",
        otherSite: "Links to another site on this tenancy. Internal, but owned by someone else.",
        internal: "Every link that stays on this tenancy, this site or another.",
        emptyText: "Links with no text on them, which a screen reader announces as the url.",
        contact: "mailto: and tel: links.",
        anchor: "Links to a position on the same page.",
        newTab: "Links written to open in a new tab.",
        insecure: "Links written as http rather than https.",
        legacy: "Links to a host recorded as retired, which are dead by definition.",
        documentsLinked: "Links whose destination is a file rather than a page.",
        checked: "Unresolved links on this tenancy that were actually requested during the run.",
    },
    charts: {
        type: "Link types",
        source: "Where links are written",
        status: "Link health",
        brokenByList: "Broken links by list",
        topTargets: "Most linked pages",
    },
    cardInfo: {
        type: "What each link points at, counted once per placement.",
        source: "Body text, web part properties, menus, config files or file content.",
        status: "Working, broken or untested once the index and the link check have run.",
        brokenByList: "Where the dead links are written, so the fixing can be handed out.",
        topTargets: "Destinations by how many places link to them.",
    },
    status: {
        yes: "Broken",
        no: "Working",
        unsure: "Untested",
        matched: "Mapped",
        unmapped: "Unmapped",
    },
    sources: {
        content: "Content",
        webpart: "Web part",
        navigation: "Navigation",
        document: "Document",
        attachment: "Attachment",
        config: "Config file",
        megamenu: "Mega menu",
    },
    types: {
        thisSite: "This site",
        otherSite: "Other site",
        share: "Share link",
        legacy: "Legacy",
        document: "Document",
        external: "External",
        anchor: "Anchor",
        contact: "Contact",
        script: "Script",
        unknown: "Unknown",
    },
    kinds: {
        page: "Page",
        item: "List item",
        document: "Document",
        navigation: "Navigation",
        attachment: "Attachment",
        config: "Config file",
        megamenu: "Mega menu",
    },
    navigationTitle: "Navigation menus",
    navigationList: "Navigation",
    configList: "Config files",
    megaMenuList: "Mega menu",
    notes: {
        external: "External links cannot be tested from the browser, so they stay untested however often they are checked.",
        documents: "Document content is downloaded and parsed in the browser, two files at a time, and files over the size limit are skipped.",
        broken: "Only unresolved links on this tenancy are requested. Everything that matched a scanned item is already known good.",
    },
    actions: {
        title: "Exports",
        description: "Everything the audit can hand to a spreadsheet. Each file opens on a summary block of the same counts shown on the overview.",
        fullAudit: "One row per link found, across every item, menu, config file and document.",
        external: "Only links leaving this tenancy, for a review of who you send people to.",
        broken: "Only links proven dead: a retired host, or an error status from the server.",
        references: "One row per scanned item with its incoming, outgoing and broken counts.",
        disabled: "Nothing to export yet.",
    },
    empty: {
        title: "No link audit yet",
        description: "Run the audit to read every page, list item, menu and document, then resolve what each link points at.",
        references: "Nothing was scanned. Check the site list and the page and item limits.",
        links: "No links were found in anything that was scanned.",
        broken: "No broken links. Nothing pointed at a legacy host and nothing answered with an error.",
        external: "No links leave this tenancy.",
        megaMenu: "No mega menu configuration was scanned. Set its path in the run settings.",
    },
    flags: {
        broken: "Broken links",
        legacy: "Legacy",
        insecure: "Insecure",
        emptyText: "No link text",
        unmapped: "Unmapped",
        orphan: "No incoming",
    },
    dialog: {
        outgoing: "Outgoing links",
        incoming: "Incoming links",
        brokenLinks: "Broken links",
        variants: "Written as",
        usedIn: "Linked from",
        noBroken: "No broken links on this item.",
        noOutgoing: "This item links to nothing.",
        noIncoming: "Nothing links to this item.",
    },
    review: "Review",
};
//# sourceMappingURL=LinkAudit.content.js.map