export const UsersAuditContent = {
  title: "Users and groups",
  description:
    "Who has an account on this site, when they first appeared, how recently their record changed, which groups they sit in, and how complete their user profiles are.",
  configTitle: "Audit settings",
  historyTitle: "Previous runs",
  moduleVersion: "Module",
  backToRuns: "All runs",
  run: "Run audit",
  rerun: "Run again",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  exportCsv: "Export CSV",
  review: "Review",
  tabs: {
    overview: "Overview",
    users: "Users",
    groups: "Groups",
  },
  stats: {
    users: "Site principals",
    people: "People",
    security: "Security groups",
    external: "External users",
    admins: "Site admins",
    system: "System accounts",
    added: "Added in window",
    active: "Active recently",
    dormant: "Not seen recently",
    groups: "SharePoint groups",
    members: "Group memberships",
    average: "Average group size",
    ungrouped: "People in no group",
    profiles: "Profiles read",
    department: "With a department",
    picture: "With a photo",
  },
  tileInfo: {
    users: "Every principal in the site user list, people and directory groups alike.",
    people: "Individual accounts, excluding directory and SharePoint groups.",
    security: "Directory groups added to the site, which bring their own membership.",
    external: "Guest accounts, identified by their login name.",
    admins: "Accounts flagged as site collection administrators.",
    system: "Service and system accounts such as the app identity, excluded from people counts when you choose.",
    added: "People whose site record was created inside the timeframe set for this run.",
    active: "People whose site record changed inside the recent window. It is a proxy for activity, not a sign in log.",
    dormant: "People whose record has not changed inside the recent window.",
    groups: "SharePoint groups on this site collection.",
    members: "Total memberships, counting a person once per group.",
    average: "Members per group, ignoring sharing link groups.",
    ungrouped: "People holding an account but no SharePoint group membership.",
    profiles: "User profiles read from the profile service for the sample.",
    department: "Sampled profiles with a department filled in.",
    picture: "Sampled profiles with a profile photo.",
  },
  charts: {
    added: "People added by month",
    active: "People last changed by month",
    kind: "Principals by type",
    members: "Members by group",
    department: "People by department",
    completeness: "Profile completeness",
  },
  cardInfo: {
    added: "When accounts first appeared on this site, by month.",
    active: "When each person's site record last changed, by month. Useful for spotting dormant accounts.",
    kind: "People against directory groups and SharePoint groups in the site user list.",
    members: "Group sizes, so oversized and empty groups stand out.",
    department: "Departments across the sampled profiles.",
    completeness: "How many sampled profiles carry a department, job title and photo.",
  },
  columns: {
    user: "User",
    kind: "Type",
    email: "Email",
    created: "First seen",
    modified: "Record changed",
    flags: "Flags",
    groups: "Groups",
    group: "Group",
    members: "Members",
    owner: "Owner",
    department: "Department",
    jobTitle: "Job title",
    office: "Office",
    properties: "Profile properties",
    photo: "Photo",
  },
  kinds: {
    user: "Person",
    securityGroup: "Security group",
    sharePointGroup: "SharePoint group",
    other: "Other",
  },
  flags: {
    external: "External",
    admin: "Site admin",
    system: "System",
    dormant: "Not seen recently",
  },
  profilesOff: "Profile reading was off for this run.",
  activityNote:
    "SharePoint does not expose a last sign in per site. First seen and record changed come from the site user information list, which updates when a person is added or their details change.",
  empty: {
    title: "No audit yet",
    description: "Run the audit to read site users, groups and profiles.",
  },
  search: {
    users: "Search users",
    groups: "Search groups",
    profiles: "Search profiles",
  },
  allGroups: "All groups",
  clearGroup: "Clear group filter",
  yes: "Yes",
  no: "No",
} as const;
